# Generated by Django 3.2.25 on 2024-04-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University',
            new_name='School',
        ),
    ]
